columnSuffix: null
handle: category
instructions: null
name: Category
searchable: false
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: false
  typeSettings:
    __assoc__:
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - 'section:5aff6ded-91b9-4ff7-aab2-5e89cd9fe12a' # Categories
  types:
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
